name: Anime Episode Notifications

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run notifier
        env:
          BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
          BREVO_SENDER_EMAIL: ${{ secrets.BREVO_SENDER_EMAIL }}
          BREVO_SENDER_NAME: ${{ secrets.BREVO_SENDER_NAME }}
        run: npm run notify

      - name: Commit cache updates
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/last-episodes.json
          git commit -m "Update episode cache" || echo "No changes"
          git push
